import type { ProviderPreset } from "@/types";

/**
 * Catalog of supported AI providers. Pre-fills baseUrl + auth shape so the
 * Settings UI only needs to ask the user for their API key.
 */
export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    shape: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    authMode: "bearer",
    envVar: "OPENROUTER_API_KEY",
    presetModels: ["openrouter/auto", "anthropic/claude-3.5-sonnet", "openai/gpt-4o-mini"],
  },
  {
    id: "stability",
    name: "Stability AI",
    shape: "custom",
    baseUrl: "https://api.stability.ai/v1",
    authMode: "bearer",
    envVar: "STABILITY_API_KEY",
    presetModels: ["stable-diffusion-xl-1024-v1-0", "stable-image-core"],
    pathOverrides: { models: "/engines/list" },
    notes: "Usado pelo Image Studio para geração de imagens.",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    shape: "custom",
    baseUrl: "https://api.elevenlabs.io/v1",
    authMode: "header",
    authHeaderName: "xi-api-key",
    envVar: "ELEVENLABS_API_KEY",
    presetModels: ["eleven_multilingual_v2", "eleven_turbo_v2_5"],
    pathOverrides: { models: "/models" },
    notes: "Usado pelo Audio Studio para voz e áudio.",
  },
  {
    id: "replicate",
    name: "Replicate",
    shape: "custom",
    baseUrl: "https://api.replicate.com/v1",
    authMode: "bearer",
    envVar: "REPLICATE_API_TOKEN",
    presetModels: ["black-forest-labs/flux-schnell", "stability-ai/stable-diffusion-3"],
    pathOverrides: { models: "/models" },
    notes: "Provider genérico para modelos multimodais hospedados no Replicate.",
  },
  {
    id: "openai",
    name: "OpenAI",
    shape: "openai",
    baseUrl: "https://api.openai.com/v1",
    authMode: "bearer",
    envVar: "OPENAI_API_KEY",
    presetModels: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o3-mini"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    shape: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    authMode: "header",
    authHeaderName: "x-api-key",
    extraHeaders: { "anthropic-version": "2023-06-01" },
    envVar: "ANTHROPIC_API_KEY",
    presetModels: ["claude-3-5-sonnet-latest", "claude-3-5-haiku-latest", "claude-3-opus-latest"],
  },
  {
    id: "groq",
    name: "Groq",
    shape: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    authMode: "bearer",
    envVar: "GROQ_API_KEY",
    presetModels: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
  },
  {
    id: "opencode",
    name: "OpenCode Zen",
    shape: "openai",
    baseUrl: "https://opencode.ai/api/v1",
    authMode: "bearer",
    presetModels: [],
  },
  {
    id: "ollama-local",
    name: "Ollama (Local)",
    shape: "ollama",
    baseUrl: "http://localhost:11434/v1",
    authMode: "none",
    presetModels: ["llama3.2", "qwen2.5-coder", "mistral"],
    notes: "Auto-detects if `ollama serve` is running on port 11434.",
  },
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    shape: "openai",
    baseUrl: "https://ollama.ai/api",
    authMode: "bearer",
    presetModels: [],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    shape: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authMode: "query",
    envVar: "GEMINI_API_KEY",
    presetModels: ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"],
  },
  {
    id: "mistral",
    name: "Mistral",
    shape: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    authMode: "bearer",
    envVar: "MISTRAL_API_KEY",
    presetModels: ["mistral-large-latest", "mistral-small-latest", "codestral-latest"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    shape: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    authMode: "bearer",
    envVar: "DEEPSEEK_API_KEY",
    presetModels: ["deepseek-chat", "deepseek-reasoner"],
  },
  {
    id: "cohere",
    name: "Cohere",
    shape: "openai",
    baseUrl: "https://api.cohere.ai/v1",
    authMode: "bearer",
    envVar: "COHERE_API_KEY",
    presetModels: ["command-r-plus", "command-r"],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    shape: "openai",
    baseUrl: "https://api.x.ai/v1",
    authMode: "bearer",
    envVar: "XAI_API_KEY",
    presetModels: ["grok-2-latest", "grok-2-mini"],
  },
  {
    id: "together",
    name: "Together AI",
    shape: "openai",
    baseUrl: "https://api.together.xyz/v1",
    authMode: "bearer",
    envVar: "TOGETHER_API_KEY",
    presetModels: ["meta-llama/Llama-3.3-70B-Instruct-Turbo"],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    shape: "openai",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    authMode: "bearer",
    envVar: "FIREWORKS_API_KEY",
    presetModels: ["accounts/fireworks/models/llama-v3p3-70b-instruct"],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    shape: "openai",
    baseUrl: "https://api.perplexity.ai",
    authMode: "bearer",
    envVar: "PERPLEXITY_API_KEY",
    presetModels: ["sonar", "sonar-pro", "sonar-reasoning"],
  },
  {
    id: "azure",
    name: "Azure OpenAI",
    shape: "openai",
    baseUrl: "https://{resource}.openai.azure.com/openai",
    authMode: "header",
    authHeaderName: "api-key",
    envVar: "AZURE_OPENAI_API_KEY",
    presetModels: [],
    extraFields: [
      { key: "resource", label: "Resource name", placeholder: "my-resource" },
      { key: "deployment", label: "Deployment name", placeholder: "gpt-4o" },
      { key: "apiVersion", label: "API version", placeholder: "2024-08-01-preview" },
    ],
    notes: "Replace {resource} in the URL with your Azure resource name.",
  },
  {
    id: "bedrock",
    name: "AWS Bedrock",
    shape: "custom",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    authMode: "none",
    presetModels: ["anthropic.claude-3-5-sonnet-20241022-v2:0"],
    extraFields: [
      { key: "accessKeyId", label: "Access key ID", type: "password" },
      { key: "secretAccessKey", label: "Secret access key", type: "password" },
      { key: "region", label: "Region", placeholder: "us-east-1" },
    ],
    notes: "Bedrock requires SigV4 signing — the backend proxy handles signing in production.",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    shape: "openai",
    baseUrl: "https://api-inference.huggingface.co/v1",
    authMode: "bearer",
    envVar: "HF_TOKEN",
    presetModels: [],
  },
  {
    id: "lmstudio",
    name: "LM Studio",
    shape: "openai",
    baseUrl: "http://localhost:1234/v1",
    authMode: "none",
    presetModels: [],
    notes: "Auto-detects local LM Studio server on port 1234.",
  },
  {
    id: "vllm",
    name: "vLLM",
    shape: "openai",
    baseUrl: "http://localhost:8000/v1",
    authMode: "none",
    presetModels: [],
  },
  {
    id: "custom",
    name: "Custom Provider",
    shape: "custom",
    baseUrl: "https://api.example.com/v1",
    authMode: "bearer",
    presetModels: [],
    notes: "Any OpenAI-compatible endpoint.",
  },
];

export function presetById(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id);
}
